Feature/use mep
caskdata/hadoop_mapr_cookbook pull request #26
Opened 2017-03-24 01:16 UTC by mattwuenschel

Mapr is using the mep repos for Mapr 5.2 and on instead of the ecosystem repo. 
http://package.mapr.com/releases/

2017-03-24 14:39 UTC, wolf31o2 requested changes
Couple questions

2017-03-24 14:39 UTC, wolf31o2 commented on recipes/repo.rb
> +    gpgcheck false
Are these packages not signed?

2017-03-24 14:39 UTC, wolf31o2 commented on recipes/repo.rb
> +  yum_ecosystem_repo_url = if node['hadoop_mapr']['distribution_version'] >= '5.2'
Shouldn't we need to make these something comparable, like floats? I think that you need to `.to_f` to convert to a float to do a >= comparison.

2017-03-24 18:13 UTC, mattwuenschel commented on recipes/repo.rb
> +    gpgcheck false
Mapr has the gpgcheck=0 for the MEP repos in the install instructions.
http://maprdocs.mapr.com/home/AdvancedInstallation/AddingMapRreposonRHorCOS.html

2017-03-24 21:43 UTC, wolf31o2 requested changes
Few more conversions to floats needed.

2017-03-24 21:43 UTC, wolf31o2 commented on recipes/repo.rb
> +    only_if { node['hadoop_mapr']['distribution_version'] < '5.2' }
Use float here, too.

2017-03-24 21:43 UTC, wolf31o2 commented on recipes/repo.rb
> +  yum_ecosystem_repo_url = if node['hadoop_mapr']['distribution_version'].to_f >= 5.2
I'd use `mapr_release.to_f` in case the version includes a 'v' as it won't convert.

2017-03-24 21:43 UTC, wolf31o2 commented on recipes/repo.rb
> +    only_if { node['hadoop_mapr']['distribution_version'] < '5.2' }
and `mapr_release.to_f`

2017-03-24 21:43 UTC, wolf31o2 commented on recipes/repo.rb
> +    gpgcheck false
:+1:

2017-03-24 21:43 UTC, wolf31o2 commented on recipes/repo.rb
> +    only_if { node['hadoop_mapr']['distribution_version'] >= '5.2' }
Here, too.

2017-03-24 21:43 UTC, wolf31o2 commented on recipes/repo.rb
> +  apt_ecosystem_repo_url = if node['hadoop_mapr']['distribution_version'] >= '5.2'
Here, too.

2017-03-24 21:43 UTC, wolf31o2 commented on recipes/repo.rb
> +    only_if { node['hadoop_mapr']['distribution_version'] < '5.2' }
Here

2017-03-24 21:43 UTC, wolf31o2 commented on recipes/repo.rb
> +    only_if { node['hadoop_mapr']['distribution_version'] >= '5.2' }
Here

2017-03-28 19:34 UTC, wolf31o2 approved these changes
👍 LGTM

2017-03-28 19:35 UTC, merged